README.md, testHelpers.js
@joeferner This PR mostly changes documentation about Promises. One significant change is that I figured out how to make this implementation work with the popular promises library Q. I also discovered the bluebird now works with node 0.8 after all. This means all 5 libraries I have test with pass all 6 cases in our test matrix.
I also realized that since the three promisified methods of the java module are not promisified until onJvmCreated that they cannot be the first java method an application calls. For now, I just recommend calling another method such as java.import() first. I considered creating a public method java.finalizeInitialization(), which would call the internal method ensureJvm(), but it seemed more trouble than it was worth, at last at the moment.
=> Clarifications to Promises implementation (mostly documentation).

.travis.yml
@joeferner What do you think? Ok to drop node 0.8 and 0.11, and just build node 0.10 and 0.12?
=> Change Travis to build against node 0.10 and 0.12. Drop 0.8.

src/methodCallBaton.cpp
Description: When making async calls, we are getting a memory leak. This change fixes this memory leak.
=> Memory Leak for Async calls

README.md, lib/nodeJavaBridge.js, package.json, testAsyncOptions/testClientBeforeError.js, testAsyncOptions/testClientBeforeThrows.js, testAsyncOptions/testClientPBeforeError.js, testAsyncOptions/testClientPBeforeThrows.js, testAsyncOptions/testDefacto.js, testAsyncOptions/testDefactoPlusPromise.js, testAsyncOptions/testInvalidLaunch.js, testAsyncOptions/testNoAsync.js
@joeferner This is a new API that we have found useful. It makes it simpler to have several semi-independent modules that encapsulate specific Java classes or libraries, and then compose these modules into a larger application.
=> Add the registerClient/ensureJvm API

src/java.cpp
@joeferner @jsdevel 
This change was prompted by #230, and the error message contained there stating that `warning: 'JNI_GetDefaultJavaVMInitArgs' is deprecated`. It's not clear to me exactly which platforms deprecate the call, but it does seem pretty clear that Oracle has considered the call unnecessary at least since Java 6. I figure we might as well remove it and see if it causes any problems on obscure platforms (but note, for me, all variants of MS Windows are obscure.)
I could just merge this but wanted to give you a both chance to stop this PR if you have relevant knowledge about JNI_GetDefaultJavaVMInitArgs on obscure platforms.
While researching it I also noticed and fixed a memory leak.
=> Remove call to JNI_GetDefaultJavaVMInitArgs

.travis.yml
@joeferner It seems that the v8 in node 4 now requires clang instead of gcc. Travis defaults to gcc, but we can specify clang by setting the env variables CC and CXX.
FYI I only added one line to the .travis.yml, but I switched the newlines from CRLF to unix, so the diff below shows every line changing.
Fixes #255.
=> Add node v4.x to travis test matrix

lib/nodeJavaBridge.js, testAsyncOptions/testClientBeforeSyncThrows.js, testAsyncOptions/testDefacto.js
With this change, we can skip the callback noise for cases that don't
need it, for example:
`java.registerClient(function() { do.some.thing(); });`
=> Allow before/after functions that don't take a callback

README.md
For whatever reasons, github requires an extra newline after html before it starts rendering markdown.  This meant that some markdown headers right after html anchor tags in the README were not displaying properly (rather, they were exposing the raw html/markdown).
I fixed it automatically using the regular expression (in vim):  
:%s/\/>\n[^\n]/\>\r\r/g
I care a lot about high quality documentation for good projects =)
=> Fix a formatting error in github markdown

src/java.cpp
xlc++ on IBM z/OS does not support casting a pthread_t to a long. The following changes will fix the issue while still supporting other compilers.
Developed in consultation with @adnanhemani
=> z/OS xlc++ support changes

README.md
There is small misinterpretation in README file: class declared inside another class is actually called [nested class](https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html). This pull request fixes the issue.
=> Fix Java terminology in README

binding.gyp, find_java_libdir.sh
I just opened issue #437 and have a partial solution. The binding.gyp file still doesn't set the target_arch variable within node-gyp. I wasn't able to get it to work and had to override the variable at the command line with 'node-gyp configure build --target_arch=ppc64le'.
Thanks!
=> partial fix for node-gyp configure on ppc64le. Issue #437

binding.gyp, find_java_libdir.sh
Another possible commit that deals with this issue fully. Not sure if it's the right way to do it but it works. Rather than trying to set the *target_arch* variable in *binding.gyp* it seemed just as reasonable to leave the target architecture as ppc64 as far as node-gyp is concerned. In this version find_java_libdir.sh gets the result of `uname -m` and uses that as the architecture value in the Java lib path.
```
elif [[ "${os}" == "linux" ]] && [[ "${target_arch}" == "ppc64" || "${target_arch}" == "ppc" ]]; then
target_arch=`uname -m`
if [[ -d ${jre_dir}/${target_arch}/classic ]]; then lib_dir="${jre_dir}"/${target_arch}/classic; else lib_dir="${jre_dir}"/${target_arch}/server; fi
```
This works on my ppc64le environment and it's no longer necessary to override the node-gyp environment …
=> fix for ppc64le build that does not override target_arch in node-gyp

README.md
* typos
* changed the suggestion for implementing promisify to promisify: require('util').promisify since it will work OOTB in node 8.0.0 or newer
SUGGESTION: since node 8.0.0 is LTS and `promisify: require('util').promisify` works OOTB I suggest to change the behavior a little bit so if user provides a promiseSuffix but it doesn't provides `promisify` and `require('util').promisify` exists then use that implementation. Otherwise perform current behavior. 
Do you think such a PR makes sense ? (asking before doing it) 
Thanks. Cool project. Keep it up!
=> typos and promisify implementation

.travis.yml, package-lock.json, package.json, src/java.cpp, src/java.h, src/javaObject.cpp, src/javaObject.h, src/nodeJavaBridge.cpp, src/utils.cpp, src/utils.h
* Updates `nan`
* Switches a bunch of V8 methods to use the `Nan` helpers to retain interop and support node 12
* Manually fixes a few bits of usage that nan doesn't handle
Tested locally, all tests pass on node 12
Closes #473
Closes #470
=> feat: make node 12 compatible

src/java.cpp, src/utils.h
Fixes #262 
If you're on the v8 thread and call a proxy, node-java just calls the javascript directly.  If not, node-java queues the javascript call to get it in the main loop, then checks every 100ms to see if the javascript is done.
When the proxy object is created in C++ (based on call from javascript), a java object of type NodeDynamicProxyClass is instantiated with a single DynamicProxyData object, which pointer is passed to the constructor as a `long`.  This is the same pointer that gets passed back to Java_node_NodeDynamicProxyClass_callJs, and gets used for every subsequent call.  If two calls are occurring simultaneously or recursively, though, then it would get clobbered.
The changes here fix that by creating a separate callData object for each call.
We also switch to using …
=> Fix concurrency

README.md, docker/Dockerfile
Fixed the Dockerfile and updated jdk to `jdk-8u261-linux-x64.tar.gz` and fixed the nodejs path, now the Docker container builds.
Inside the container, installation should be done as `npm install --unsafe-perm java` to get around the following error:
```
> java@0.12.1 install /root/testing/node_modules/java
> node-gyp rebuild
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/11.2.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/testing/node_modules/java/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, stat '/root/testing/node_modules/java/.node-gyp/11.2.0'
gyp ERR! System Linux …
```
=> Fixed Dockerfile 

package-lock.json, src/utils.cpp
I was actually attempting a build for another project using this repository's latest commit to `master`. Incidentally, I ran into a `node-gyp` error, with this message:
```
../src/utils.cpp: In function 'v8::Local<v8::ArrayBuffer> newArrayBuffer(void*, size_t)':
../src/utils.cpp:488:16: error: 'class v8::ArrayBuffer' has no member named 'GetBackingStore'
488 |     memcpy(ab->GetBackingStore()->Data(), elems, length);
|                ^~~~~~~~~~~~~~~
```
Here is the `node-gyp` build environment metadata:
```
gyp info using node-gyp@7.1.0
gyp info using node@10.22.0 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
```
For reference, I've attached the full `node-gyp` output [here in this file](https://github.com/joeferner/node-java/files/5116095/node-g …
=> V8 Bindings Compatibility Fix

package-lock.json, package.json
@joeferner  PTAL Thx.
Some audit isues that cropped up - fixed via `npm audit fix`.
=> Audit fixes `npm audit fix` for y18n, lodash and hosted-git-info modules

lib/nodeJavaBridge.js
Only notable behaviour broken with empty string promise suffix was static method calls on imported classes.
(java.import('...').staticMethod())
This is due to double-promisification of callStaticMethod function. This change extracts raw, pre-promisified methods used later in runtime by java bridge as local variables and uses that instead.
This also fixes a similar breakage if someone set "Sync" as promise suffix.
=> fix empty string promise suffix

src/java.cpp, src/java.h
It breaks the internal indefinite loop and allows Node process to quit without SIGTERM.
Solves bug #539 - The process refuses to quit.
=> Added stop() method to java object.
